# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_gw',
        ),
    ]
