# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminex', '0002_auto_20160819_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_gw',
        ),
    ]
